apiVersion: v1
kind: Service
metadata:
  name: {{ include "spies-helm-chart.fullname" . }}
  labels:
    {{- include "spies-helm-chart.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "spies-helm-chart.selectorLabels" . | nindent 4 }}
