# permissions for end users to edit spies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spies-editor-role
rules:
- apiGroups:
  - charts.my.domain
  resources:
  - spies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - charts.my.domain
  resources:
  - spies/status
  verbs:
  - get
